# Generated by Django 4.1.7 on 2023-03-23 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='images/barbers')),
                ('phone_number', models.IntegerField(max_length=15)),
                ('email', models.EmailField(max_length=100)),
                ('instragram', models.CharField(blank=True, max_length=500)),
                ('facebook', models.CharField(blank=True, max_length=500)),
                ('twitter', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'Barber',
                'verbose_name_plural': 'Barbers',
            },
        ),
    ]
