# Generated by Django 4.1.7 on 2023-03-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='first_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
