# Generated by Django 4.1.7 on 2023-03-25 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '__first__'),
        ('Appointment', '0004_alter_appointments_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.services'),
        ),
    ]
