# Generated by Django 4.1.7 on 2023-03-25 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0005_alter_appointments_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='day',
            field=models.CharField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default='Monday', max_length=10),
        ),
    ]
