# Generated by Django 4.1.7 on 2023-03-21 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_typeofservice_delete_services'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typeofservice',
            options={'verbose_name': 'Types of Service', 'verbose_name_plural': 'Types of Service'},
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('price', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=100)),
                ('type_of_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.typeofservice')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
    ]
