# Generated by Django 4.1.7 on 2023-03-21 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_businesshours_is_closed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businesshours',
            old_name='weekday',
            new_name='day',
        ),
    ]
