# Generated by Django 4.1.7 on 2023-03-23 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0003_barbers_title'),
        ('appointments', '0006_alter_appointments_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='barber',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='barbers.barbers'),
        ),
    ]
